### ISSUE TITLE
bug(dropdown): little dot appearing

### ISSUE THREAD

**Issue by rosset-nocpes** [olexh/hikka-next#5]
Маленька точка з'являється коли відкривається dropdown меню (поки помітив це тільки у navbar)

https://github.com/olexh/hikka-next/assets/53056080/92724f1f-4c82-4e38-99d3-0f9175fc58b3

**Comment by olexh** [comment]
Поки що не можу відтворити в себе. @rosset-nocpes переглянь, будь ласка, чи є така проблема в документації Shadcn цієї компоненти - https://ui.shadcn.com/docs/components/navigation-menu

**Comment by rosset-nocpes** [comment]
Так, це проблема у самого shadcn/ui
